### ISSUE TITLE
Duplicate symbols

### ISSUE THREAD

**Issue by jabberwalky** [AdTapsy/AdTapsy-iOS-SDK#1]
`duplicate symbol _OBJC_CLASS_$_IMMraidFetcherDAO in:
    /Users/StasTomych/Projects/Zalunu/prj/AdTapsy/AdNetworks/InMobi-iOS-SDK/libInMobi.a(IMMraidFetcher.o)
    /Users/StasTomych/Projects/Zalunu/prj/AdTapsy/AdNetworks/InMobi-iOS-SDK/libInMobi.a(IMMraidFetcherDAO.o)
duplicate symbol _OBJC_METACLASS_$_IMMraidFetcherDAO in:
    /Users/StasTomych/Projects/Zalunu/prj/AdTapsy/AdNetworks/InMobi-iOS-SDK/libInMobi.a(IMMraidFetcher.o)
    /Users/StasTomych/Projects/Zalunu/prj/AdTapsy/AdNetworks/InMobi-iOS-SDK/libInMobi.a(IMMraidFetcherDAO.o)`

**Comment by bgizdov** [comment]
Hi jabberwalky,

Can you check for old inmobi library in your project and also library search paths?

Regards,
Borislav.
